apiVersion: v1
kind: Namespace
metadata:
  name: edge
  labels:
    name: edge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivemq-edge
  template:
    metadata:
      labels:
        app: hivemq-edge
    spec:
      containers:
      - name: hivemq-edge
        image: hivemq/hivemq-edge:latest
        ports:
        - containerPort: 1883
        - containerPort: 8080
        env:
        - name: HIVEMQ_CONTROL_CENTER_USER
          value: "admin"
        - name: HIVEMQ_CONTROL_CENTER_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: hivemq-edge
  namespace: edge
spec:
  selector:
    app: hivemq-edge
  ports:
    - protocol: TCP
      name: mqtt
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: ui
      port: 8080
      targetPort: 8080

